app.use(cors({
 origin:[
   "http://localhost:3000",
   "http://localhost:3001",
   "https://gadget-hub-admin.vercel.app",
   "https://shop.gadgethub.in"
 ],
 methods:["GET","POST","PUT","DELETE","PATCH"],
 credentials:true
}))
